---
title: "Insurance and Outliers - Identifying Outliers with Isolation Forests"
output: html_notebook
---



<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p>The following is a brief extension to the previous analysis regarding appropriate regression modelling on the health insurance dataset, depending on the outliers present within. The focus here is more on the exploratory stage of data analysis in terms of identifying the outliers themselves in the dataset. Specifically, the use of the Isolation Forests algorithm will be described and demonstrated for outlier/anomaly detection. As in-depth data exploration has already been carried out in the previous analysis, it will not be repeated here.</p>
<p>Both R and Python are used for this analysis. The standard Python libraries are loaded.</p>
<pre class="python"><code>#Python

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt</code></pre>
</div>
<div id="visually-identified-outliers" class="section level3">
<h3>Visually Identified Outliers</h3>
<p>The categorical variables are converted into dummy variables using one-hot encoding to allow the algorithm to operate effectively.</p>
<pre class="python"><code>#Python

insurance = pd.read_csv(&#39;insurance.csv&#39;)

encode = pd.get_dummies(insurance[[&#39;sex&#39;,&#39;smoker&#39;,&#39;region&#39;]])

insurance_encode = pd.concat([encode,insurance],
                             axis = 1)

insurance_encode = insurance_encode.drop([&#39;sex&#39;,&#39;smoker&#39;,&#39;region&#39;],axis = 1)</code></pre>
<p>When it comes to identifying outliers, one highly simple method would be to identify such values visually using charts and graphs. In the previous analysis, when comparing the charges variable against age and bmi, some outlier values were identified in this manner. These seven outliers were seen in the charges variable where the value was exceeding 50000. A detailed look at these seven observations is shown below.</p>
<pre class="python"><code>#Python

#7 outliers observed during exploratory analysis
gt_50000 = insurance[insurance[&#39;charges&#39;] &gt; 50000]</code></pre>
<pre class="r"><code>#R

py$gt_50000</code></pre>
<pre><code>##      age    sex    bmi children smoker    region  charges
## 34    28   male 36.400        1    yes southwest 51194.56
## 543   54 female 47.410        0    yes southeast 63770.43
## 577   31 female 38.095        1    yes northeast 58571.07
## 819   33 female 35.530        0    yes northwest 55135.40
## 1146  60   male 32.800        0    yes southwest 52590.83
## 1230  52   male 34.485        3    yes northwest 60021.40
## 1300  45   male 30.360        0    yes southeast 62592.87</code></pre>
<p>Aside from the indication that only smokers are being charged such high premiums, none of the other explanatory variables provide a similar confident indication, with their values varying significantly. For instance, within these 7 observations, all four regions are being included as those being charged a high amount of premiums.</p>
</div>
<div id="isolation-forests" class="section level3">
<h3>Isolation Forests</h3>
<p>The issue with identifying outliers visually is that perspective is limited only to the variables that are being considered in the chart. Since at a maximum only 3 variables can be considered simultaneously in a chart, the process of identifying outlier observations/anomalies can become increasingly tedious as the number of features to consider increases. In order to counteract this, there are various algorithms available which can process an entire dataset and provide a reasonable identification of the outliers in a data via unsupervised learning techniques. One such method is known as Isolation Forests.</p>
<p>Isolation Forests essentially follow the same principles as decision trees and random forests, as in it develops various trees and combines the results from all of them to identify outliers. The way is does this is based on how the tree itself is constructed. A tree is constructed by randomly selecting a feature/variable, then randomly selecting a value between the minimum and maximum of that feature upon which a split can be created for the next feature selected, and the process is repeated till a desired tree depth is reached. The very first split is known as the root node, and the final splits are known as the leaf nodes. Keeping this process in mind, the way isolation forests identify outliers using this tree building mechanism is that assuming that outliers are few and significantly different from other observations, the ‘branches’ (path lengths) created by outlier values during the tree building process will be much shorter than those of other standard observations. By identifying the shortest paths, isolation forests are able to effectively identify anomalies in the data.</p>
<p>To identify outliers in this insurance dataset, the isolation forests algorithm is applied below. All hyperparameter values are kept at their default except for n_estimator, which is changed from 100 to 500 for a higher number of trees to be created in the forest. A random state value is also set for reproducibility due to the random element of this algorithm.</p>
<pre class="python"><code>#Python

from sklearn.ensemble import IsolationForest

i_forest = IsolationForest(n_estimators=500,
                           contamination=0.1,
                           random_state=1234,
                           max_samples=&#39;auto&#39;)

outliers_forest = i_forest.fit_predict(insurance_encode)

outliers_forest = outliers_forest.reshape(-1,1)

insurance_encode[&#39;outliers_forest&#39;] = outliers_forest

forest_outliers = insurance_encode[insurance_encode[&#39;outliers_forest&#39;] == -1]</code></pre>
<p>The algorithm identifies anomalies by labelling them -1. These observations are filtered into a separate dataframe.</p>
<pre class="r"><code>#R

f_o &lt;- py$forest_outliers</code></pre>
</div>
<div id="key-observations" class="section level3">
<h3>Key Observations</h3>
<p>A summary statistics table for these outlier observations is shown below. A total of 134 observations have been classified as outliers from 1338 rows.</p>
<pre class="r"><code>#R

x &lt;- c(1:8,11)

for (i in x) {
  f_o[,i] &lt;- as.factor(f_o[,i])
}

rm(x,i)

pander::pander(summary(f_o[,-13]))</code></pre>
<table style="width:94%;">
<caption>Table continues below</caption>
<colgroup>
<col width="18%" />
<col width="15%" />
<col width="16%" />
<col width="18%" />
<col width="26%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">sex_female</th>
<th align="center">sex_male</th>
<th align="center">smoker_no</th>
<th align="center">smoker_yes</th>
<th align="center">region_northeast</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0:58</td>
<td align="center">0:76</td>
<td align="center">0:131</td>
<td align="center">0: 3</td>
<td align="center">0:108</td>
</tr>
<tr class="even">
<td align="center">1:76</td>
<td align="center">1:58</td>
<td align="center">1: 3</td>
<td align="center">1:131</td>
<td align="center">1: 26</td>
</tr>
<tr class="odd">
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
<tr class="even">
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
<tr class="odd">
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
<tr class="even">
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
</tbody>
</table>
<table>
<caption>Table continues below</caption>
<colgroup>
<col width="26%" />
<col width="26%" />
<col width="26%" />
<col width="21%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">region_northwest</th>
<th align="center">region_southeast</th>
<th align="center">region_southwest</th>
<th align="center">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0:92</td>
<td align="center">0:102</td>
<td align="center">0:100</td>
<td align="center">Min. :18.00</td>
</tr>
<tr class="even">
<td align="center">1:42</td>
<td align="center">1: 32</td>
<td align="center">1: 34</td>
<td align="center">1st Qu.:25.00</td>
</tr>
<tr class="odd">
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">Median :39.50</td>
</tr>
<tr class="even">
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">Mean :40.06</td>
</tr>
<tr class="odd">
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">3rd Qu.:54.00</td>
</tr>
<tr class="even">
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">Max. :64.00</td>
</tr>
</tbody>
</table>
<table style="width:60%;">
<colgroup>
<col width="22%" />
<col width="15%" />
<col width="22%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">bmi</th>
<th align="center">children</th>
<th align="center">charges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Min. :17.20</td>
<td align="center">0:49</td>
<td align="center">Min. : 6666</td>
</tr>
<tr class="even">
<td align="center">1st Qu.:24.94</td>
<td align="center">1:16</td>
<td align="center">1st Qu.:20400</td>
</tr>
<tr class="odd">
<td align="center">Median :31.09</td>
<td align="center">2:29</td>
<td align="center">Median :35217</td>
</tr>
<tr class="even">
<td align="center">Mean :31.16</td>
<td align="center">3:33</td>
<td align="center">Mean :33331</td>
</tr>
<tr class="odd">
<td align="center">3rd Qu.:36.46</td>
<td align="center">4: 4</td>
<td align="center">3rd Qu.:44362</td>
</tr>
<tr class="even">
<td align="center">Max. :52.58</td>
<td align="center">5: 3</td>
<td align="center">Max. :63770</td>
</tr>
</tbody>
</table>
<p>Some key observations can be made about these outliers from the summary table:</p>
<ul>
<li>Majority of the individuals in these observations are classified as smokers (131 from 134 total)</li>
<li>Approximately 57% of these individuals are women (76/134)</li>
<li>Among the regions, most belong to the north west and least to the north east</li>
<li>Majority of these outliers are individuals with no children.</li>
<li>Within the strictly numerical variables (age, bmi and charges), a relatively normal distribution can be seen as evidenced by the minimal differences between the mean and median values for each. In the charges variable however, it is interesting to note that aside from the minimum value of 6666, from the first quartile to the maximum, all values are above 20000. This indicates that majority of the outlier observations involve higher premiums being charged to the individual, if compared to mean (13270) and median (9382) values of this variable in the context of the entire dataset shown in the previous analysis.</li>
</ul>
<p>Once such outlier values are identified, they can be managed according to the requirements of the analysis. As this is unsupervised learning, it cannot be said with certainty whether all the outliers identified are indeed 100% accurate. However, by analysing the statistics of such observations to highlight unreasonable observations, and by tuning the hyperparameters of the algorithm, anomalies can be consistently identified with improved accuracy.</p>
</div>
